POST https://comment--hawksworx.netlify.com/stubs/comments/thanks HTTP/1.1
Content-Type: application/x-www-form-urlencoded

{
  "form-name": "approved-blog-comments",
  "payload" : {
    "path": "/blog/smashing-magazine-moves-to-a-jam-stack-architecture/",
    "email": "phil@netlify.com",
    "name": "phil",
    "comment": "test comment thanks",
    "date": "2018-02-11T10:48:13.431Z"
  }
}

###
curl -X POST -H "Content-Type":"application/x-www-form-urlencoded" -d '{form-name:"approved-blog-comments", payload: { name:"Curly Phil"}}' https://www.hawksworx.com/thanks
